POST http://localhost:8000/subscriptions
Content-Type: application/x-www-form-urlencoded

name=le%20guin&email=ursula3_le_guin%40gmail.com


###


GET http://localhost:8000/health_check


###

POST http://localhost:8000/rename
Content-Type: application/x-www-form-urlencoded

name=le%20guin99999&email=ursula_le_guin%40gmail.com


###