app:
  port: 8000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "hi@gpu.land"
  auth_token: "9be7c3ae-4cd7-4582-8a1d-0cfdb9f0c402"
